services:
  redis:
    image: redis:7-alpine
    container_name: jfh-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - jfh-redis-data:/data

volumes:
  jfh-redis-data:
